//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetScape.AnalysisWork.RequestNote1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Request", Namespace="http://www.gzsums.net/requisition/")]
    [System.SerializableAttribute()]
    public partial class Request : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NetScape.AnalysisWork.RequestNote1.RequestHeader requestHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string requestBodyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public NetScape.AnalysisWork.RequestNote1.RequestHeader requestHeader {
            get {
                return this.requestHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.requestHeaderField, value) != true)) {
                    this.requestHeaderField = value;
                    this.RaisePropertyChanged("requestHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string requestBody {
            get {
                return this.requestBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.requestBodyField, value) != true)) {
                    this.requestBodyField = value;
                    this.RaisePropertyChanged("requestBody");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestHeader", Namespace="http://www.gzsums.net/requisition/")]
    [System.SerializableAttribute()]
    public partial class RequestHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string senderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string requestTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgPriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                if ((object.ReferenceEquals(this.senderField, value) != true)) {
                    this.senderField = value;
                    this.RaisePropertyChanged("sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string receiver {
            get {
                return this.receiverField;
            }
            set {
                if ((object.ReferenceEquals(this.receiverField, value) != true)) {
                    this.receiverField = value;
                    this.RaisePropertyChanged("receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string requestTime {
            get {
                return this.requestTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.requestTimeField, value) != true)) {
                    this.requestTimeField = value;
                    this.RaisePropertyChanged("requestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgType {
            get {
                return this.msgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.msgTypeField, value) != true)) {
                    this.msgTypeField = value;
                    this.RaisePropertyChanged("msgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgId {
            get {
                return this.msgIdField;
            }
            set {
                if ((object.ReferenceEquals(this.msgIdField, value) != true)) {
                    this.msgIdField = value;
                    this.RaisePropertyChanged("msgId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string msgPriority {
            get {
                return this.msgPriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.msgPriorityField, value) != true)) {
                    this.msgPriorityField = value;
                    this.RaisePropertyChanged("msgPriority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string msgVersion {
            get {
                return this.msgVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.msgVersionField, value) != true)) {
                    this.msgVersionField = value;
                    this.RaisePropertyChanged("msgVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://www.gzsums.net/requisition/")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NetScape.AnalysisWork.RequestNote1.ResponseHeader responseHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responseBodyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public NetScape.AnalysisWork.RequestNote1.ResponseHeader responseHeader {
            get {
                return this.responseHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.responseHeaderField, value) != true)) {
                    this.responseHeaderField = value;
                    this.RaisePropertyChanged("responseHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string responseBody {
            get {
                return this.responseBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.responseBodyField, value) != true)) {
                    this.responseBodyField = value;
                    this.RaisePropertyChanged("responseBody");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseHeader", Namespace="http://www.gzsums.net/requisition/")]
    [System.SerializableAttribute()]
    public partial class ResponseHeader : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string senderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string receiverField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string requestTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgPriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string errMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                if ((object.ReferenceEquals(this.senderField, value) != true)) {
                    this.senderField = value;
                    this.RaisePropertyChanged("sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string receiver {
            get {
                return this.receiverField;
            }
            set {
                if ((object.ReferenceEquals(this.receiverField, value) != true)) {
                    this.receiverField = value;
                    this.RaisePropertyChanged("receiver");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string requestTime {
            get {
                return this.requestTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.requestTimeField, value) != true)) {
                    this.requestTimeField = value;
                    this.RaisePropertyChanged("requestTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string msgType {
            get {
                return this.msgTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.msgTypeField, value) != true)) {
                    this.msgTypeField = value;
                    this.RaisePropertyChanged("msgType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string msgId {
            get {
                return this.msgIdField;
            }
            set {
                if ((object.ReferenceEquals(this.msgIdField, value) != true)) {
                    this.msgIdField = value;
                    this.RaisePropertyChanged("msgId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string msgPriority {
            get {
                return this.msgPriorityField;
            }
            set {
                if ((object.ReferenceEquals(this.msgPriorityField, value) != true)) {
                    this.msgPriorityField = value;
                    this.RaisePropertyChanged("msgPriority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string msgVersion {
            get {
                return this.msgVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.msgVersionField, value) != true)) {
                    this.msgVersionField = value;
                    this.RaisePropertyChanged("msgVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string errCode {
            get {
                return this.errCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.errCodeField, value) != true)) {
                    this.errCodeField = value;
                    this.RaisePropertyChanged("errCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string errMessage {
            get {
                return this.errMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.errMessageField, value) != true)) {
                    this.errMessageField = value;
                    this.RaisePropertyChanged("errMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.gzsums.net/requisition/", ConfigurationName="RequestNote1.RequestNoteSoap")]
    public interface RequestNoteSoap {
        
        // CODEGEN: 命名空间 http://www.gzsums.net/requisition/ 的元素名称 req 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gzsums.net/requisition/RisReservationReceive", ReplyAction="*")]
        NetScape.AnalysisWork.RequestNote1.RisReservationReceiveResponse RisReservationReceive(NetScape.AnalysisWork.RequestNote1.RisReservationReceive request);
        
        // CODEGEN: 命名空间 http://www.gzsums.net/requisition/ 的元素名称 req 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gzsums.net/requisition/RequisitionFind", ReplyAction="*")]
        NetScape.AnalysisWork.RequestNote1.RequisitionFindResponse RequisitionFind(NetScape.AnalysisWork.RequestNote1.RequisitionFind request);
        
        // CODEGEN: 命名空间 http://www.gzsums.net/requisition/ 的元素名称 req 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gzsums.net/requisition/RequisitionAdd", ReplyAction="*")]
        NetScape.AnalysisWork.RequestNote1.RequisitionAddResponse RequisitionAdd(NetScape.AnalysisWork.RequestNote1.RequisitionAdd request);
        
        // CODEGEN: 命名空间 http://www.gzsums.net/requisition/ 的元素名称 req 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.gzsums.net/requisition/RequisitionPayInfo", ReplyAction="*")]
        NetScape.AnalysisWork.RequestNote1.RequisitionPayInfoResponse RequisitionPayInfo(NetScape.AnalysisWork.RequestNote1.RequisitionPayInfo request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RisReservationReceive {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RisReservationReceive", Namespace="http://www.gzsums.net/requisition/", Order=0)]
        public NetScape.AnalysisWork.RequestNote1.RisReservationReceiveBody Body;
        
        public RisReservationReceive() {
        }
        
        public RisReservationReceive(NetScape.AnalysisWork.RequestNote1.RisReservationReceiveBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gzsums.net/requisition/")]
    public partial class RisReservationReceiveBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NetScape.AnalysisWork.RequestNote1.Request req;
        
        public RisReservationReceiveBody() {
        }
        
        public RisReservationReceiveBody(NetScape.AnalysisWork.RequestNote1.Request req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RisReservationReceiveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RisReservationReceiveResponse", Namespace="http://www.gzsums.net/requisition/", Order=0)]
        public NetScape.AnalysisWork.RequestNote1.RisReservationReceiveResponseBody Body;
        
        public RisReservationReceiveResponse() {
        }
        
        public RisReservationReceiveResponse(NetScape.AnalysisWork.RequestNote1.RisReservationReceiveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gzsums.net/requisition/")]
    public partial class RisReservationReceiveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NetScape.AnalysisWork.RequestNote1.Response RisReservationReceiveResult;
        
        public RisReservationReceiveResponseBody() {
        }
        
        public RisReservationReceiveResponseBody(NetScape.AnalysisWork.RequestNote1.Response RisReservationReceiveResult) {
            this.RisReservationReceiveResult = RisReservationReceiveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequisitionFind {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequisitionFind", Namespace="http://www.gzsums.net/requisition/", Order=0)]
        public NetScape.AnalysisWork.RequestNote1.RequisitionFindBody Body;
        
        public RequisitionFind() {
        }
        
        public RequisitionFind(NetScape.AnalysisWork.RequestNote1.RequisitionFindBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gzsums.net/requisition/")]
    public partial class RequisitionFindBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NetScape.AnalysisWork.RequestNote1.Request req;
        
        public RequisitionFindBody() {
        }
        
        public RequisitionFindBody(NetScape.AnalysisWork.RequestNote1.Request req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequisitionFindResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequisitionFindResponse", Namespace="http://www.gzsums.net/requisition/", Order=0)]
        public NetScape.AnalysisWork.RequestNote1.RequisitionFindResponseBody Body;
        
        public RequisitionFindResponse() {
        }
        
        public RequisitionFindResponse(NetScape.AnalysisWork.RequestNote1.RequisitionFindResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gzsums.net/requisition/")]
    public partial class RequisitionFindResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NetScape.AnalysisWork.RequestNote1.Response RequisitionFindResult;
        
        public RequisitionFindResponseBody() {
        }
        
        public RequisitionFindResponseBody(NetScape.AnalysisWork.RequestNote1.Response RequisitionFindResult) {
            this.RequisitionFindResult = RequisitionFindResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequisitionAdd {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequisitionAdd", Namespace="http://www.gzsums.net/requisition/", Order=0)]
        public NetScape.AnalysisWork.RequestNote1.RequisitionAddBody Body;
        
        public RequisitionAdd() {
        }
        
        public RequisitionAdd(NetScape.AnalysisWork.RequestNote1.RequisitionAddBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gzsums.net/requisition/")]
    public partial class RequisitionAddBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NetScape.AnalysisWork.RequestNote1.Request req;
        
        public RequisitionAddBody() {
        }
        
        public RequisitionAddBody(NetScape.AnalysisWork.RequestNote1.Request req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequisitionAddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequisitionAddResponse", Namespace="http://www.gzsums.net/requisition/", Order=0)]
        public NetScape.AnalysisWork.RequestNote1.RequisitionAddResponseBody Body;
        
        public RequisitionAddResponse() {
        }
        
        public RequisitionAddResponse(NetScape.AnalysisWork.RequestNote1.RequisitionAddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gzsums.net/requisition/")]
    public partial class RequisitionAddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NetScape.AnalysisWork.RequestNote1.Response RequisitionAddResult;
        
        public RequisitionAddResponseBody() {
        }
        
        public RequisitionAddResponseBody(NetScape.AnalysisWork.RequestNote1.Response RequisitionAddResult) {
            this.RequisitionAddResult = RequisitionAddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequisitionPayInfo {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequisitionPayInfo", Namespace="http://www.gzsums.net/requisition/", Order=0)]
        public NetScape.AnalysisWork.RequestNote1.RequisitionPayInfoBody Body;
        
        public RequisitionPayInfo() {
        }
        
        public RequisitionPayInfo(NetScape.AnalysisWork.RequestNote1.RequisitionPayInfoBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gzsums.net/requisition/")]
    public partial class RequisitionPayInfoBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NetScape.AnalysisWork.RequestNote1.Request req;
        
        public RequisitionPayInfoBody() {
        }
        
        public RequisitionPayInfoBody(NetScape.AnalysisWork.RequestNote1.Request req) {
            this.req = req;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequisitionPayInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequisitionPayInfoResponse", Namespace="http://www.gzsums.net/requisition/", Order=0)]
        public NetScape.AnalysisWork.RequestNote1.RequisitionPayInfoResponseBody Body;
        
        public RequisitionPayInfoResponse() {
        }
        
        public RequisitionPayInfoResponse(NetScape.AnalysisWork.RequestNote1.RequisitionPayInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.gzsums.net/requisition/")]
    public partial class RequisitionPayInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NetScape.AnalysisWork.RequestNote1.Response RequisitionPayInfoResult;
        
        public RequisitionPayInfoResponseBody() {
        }
        
        public RequisitionPayInfoResponseBody(NetScape.AnalysisWork.RequestNote1.Response RequisitionPayInfoResult) {
            this.RequisitionPayInfoResult = RequisitionPayInfoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RequestNoteSoapChannel : NetScape.AnalysisWork.RequestNote1.RequestNoteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RequestNoteSoapClient : System.ServiceModel.ClientBase<NetScape.AnalysisWork.RequestNote1.RequestNoteSoap>, NetScape.AnalysisWork.RequestNote1.RequestNoteSoap {
        
        public RequestNoteSoapClient() {
        }
        
        public RequestNoteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RequestNoteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestNoteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RequestNoteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetScape.AnalysisWork.RequestNote1.RisReservationReceiveResponse NetScape.AnalysisWork.RequestNote1.RequestNoteSoap.RisReservationReceive(NetScape.AnalysisWork.RequestNote1.RisReservationReceive request) {
            return base.Channel.RisReservationReceive(request);
        }
        
        public NetScape.AnalysisWork.RequestNote1.Response RisReservationReceive(NetScape.AnalysisWork.RequestNote1.Request req) {
            NetScape.AnalysisWork.RequestNote1.RisReservationReceive inValue = new NetScape.AnalysisWork.RequestNote1.RisReservationReceive();
            inValue.Body = new NetScape.AnalysisWork.RequestNote1.RisReservationReceiveBody();
            inValue.Body.req = req;
            NetScape.AnalysisWork.RequestNote1.RisReservationReceiveResponse retVal = ((NetScape.AnalysisWork.RequestNote1.RequestNoteSoap)(this)).RisReservationReceive(inValue);
            return retVal.Body.RisReservationReceiveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetScape.AnalysisWork.RequestNote1.RequisitionFindResponse NetScape.AnalysisWork.RequestNote1.RequestNoteSoap.RequisitionFind(NetScape.AnalysisWork.RequestNote1.RequisitionFind request) {
            return base.Channel.RequisitionFind(request);
        }
        
        public NetScape.AnalysisWork.RequestNote1.Response RequisitionFind(NetScape.AnalysisWork.RequestNote1.Request req) {
            NetScape.AnalysisWork.RequestNote1.RequisitionFind inValue = new NetScape.AnalysisWork.RequestNote1.RequisitionFind();
            inValue.Body = new NetScape.AnalysisWork.RequestNote1.RequisitionFindBody();
            inValue.Body.req = req;
            NetScape.AnalysisWork.RequestNote1.RequisitionFindResponse retVal = ((NetScape.AnalysisWork.RequestNote1.RequestNoteSoap)(this)).RequisitionFind(inValue);
            return retVal.Body.RequisitionFindResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetScape.AnalysisWork.RequestNote1.RequisitionAddResponse NetScape.AnalysisWork.RequestNote1.RequestNoteSoap.RequisitionAdd(NetScape.AnalysisWork.RequestNote1.RequisitionAdd request) {
            return base.Channel.RequisitionAdd(request);
        }
        
        public NetScape.AnalysisWork.RequestNote1.Response RequisitionAdd(NetScape.AnalysisWork.RequestNote1.Request req) {
            NetScape.AnalysisWork.RequestNote1.RequisitionAdd inValue = new NetScape.AnalysisWork.RequestNote1.RequisitionAdd();
            inValue.Body = new NetScape.AnalysisWork.RequestNote1.RequisitionAddBody();
            inValue.Body.req = req;
            NetScape.AnalysisWork.RequestNote1.RequisitionAddResponse retVal = ((NetScape.AnalysisWork.RequestNote1.RequestNoteSoap)(this)).RequisitionAdd(inValue);
            return retVal.Body.RequisitionAddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NetScape.AnalysisWork.RequestNote1.RequisitionPayInfoResponse NetScape.AnalysisWork.RequestNote1.RequestNoteSoap.RequisitionPayInfo(NetScape.AnalysisWork.RequestNote1.RequisitionPayInfo request) {
            return base.Channel.RequisitionPayInfo(request);
        }
        
        public NetScape.AnalysisWork.RequestNote1.Response RequisitionPayInfo(NetScape.AnalysisWork.RequestNote1.Request req) {
            NetScape.AnalysisWork.RequestNote1.RequisitionPayInfo inValue = new NetScape.AnalysisWork.RequestNote1.RequisitionPayInfo();
            inValue.Body = new NetScape.AnalysisWork.RequestNote1.RequisitionPayInfoBody();
            inValue.Body.req = req;
            NetScape.AnalysisWork.RequestNote1.RequisitionPayInfoResponse retVal = ((NetScape.AnalysisWork.RequestNote1.RequestNoteSoap)(this)).RequisitionPayInfo(inValue);
            return retVal.Body.RequisitionPayInfoResult;
        }
    }
}
